version: '2'
services:
  graphql: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: graphql
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=graphql

    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local